# Generated by Django 3.2.6 on 2021-09-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('text', models.TextField(blank=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, verbose_name='Dominio')),
                ('server', models.CharField(max_length=255, verbose_name='Servidor')),
                ('client_email', models.CharField(max_length=255, verbose_name='Email cliente')),
                ('operator_email', models.CharField(max_length=255, verbose_name='Email operador')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], max_length=255, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('new', 'nuevo'), ('in_proccess', 'en proceso'), ('wait_for_reply', 'esperando confirmacion'), ('finalize', 'finalizado')], max_length=255, verbose_name='Estado')),
                ('area', models.CharField(choices=[('technical', 'Tecnico'), ('commercial', 'Comercial'), ('payments', 'Pagos')], max_length=255, verbose_name='Area')),
                ('operator', models.CharField(max_length=255, verbose_name='Operador')),
                ('respuesta', models.BooleanField(default=False, verbose_name='Esperando respuesta')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('content', models.ManyToManyField(to='tickets.Comment', verbose_name='Contenido')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
