# Generated by Django 3.2.6 on 2021-09-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('text', models.TextField(blank=True, verbose_name='Contenido')),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'Historys',
            },
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='content',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='comment',
        ),
        migrations.AddField(
            model_name='ticket',
            name='comment',
            field=models.ManyToManyField(blank=True, to='tickets.Comment', verbose_name='Comentario'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='history',
            field=models.ManyToManyField(to='tickets.History', verbose_name='Contenido'),
        ),
    ]
