# Generated by Django 3.2.6 on 2021-09-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20210927_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, max_length=255, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='history',
            name='text',
            field=models.TextField(blank=True, max_length=255, verbose_name='Contenido'),
        ),
    ]
