# Generated by Django 3.2.6 on 2021-09-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20210927_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, max_length=255, verbose_name='Historia'),
        ),
    ]
