# Generated by Django 3.2.6 on 2021-09-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20210927_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='history',
            field=models.ManyToManyField(to='tickets.History', verbose_name='Hystoria'),
        ),
    ]
