# Generated by Django 3.2.6 on 2021-09-28 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0006_alter_ticket_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='history',
            field=models.ManyToManyField(to='tickets.History', verbose_name='Historia'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='operator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Operador'),
        ),
    ]
