# Generated by Django 3.2.6 on 2021-09-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20210927_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='operator',
            field=models.CharField(max_length=255, verbose_name='Operador'),
        ),
    ]
