# Generated by Django 3.2.6 on 2021-09-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_remove_ticket_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='operator',
            field=models.CharField(default=1, max_length=255, verbose_name='Operador'),
            preserve_default=False,
        ),
    ]
